### ISSUE TITLE
RegionCreationException with Unity + Mef integration and Prism and Regions

### ISSUE THREAD

**Issue by salfab** [MefContrib/MefContrib#14]
Hello, 

I've been trying to figure out how to get MEF and Unity to play nice in a prism context.

Using MEF + Unity can work for some people, but I couldn't figure out how to get it working correctly with prism.

I have a project that runs okay with the integration layer, only when I add a region to the Shell view, a RegionCreationException is thrown, stating that the key couldn't be found in a dictionary.

If a sample project is required for repro purposes, please contact me and I'll provide you one.

the exception is the following :  (Note that 'ActionsRegion' is the name of a region in the xaml for the Shell view.)

Microsoft.Practices.Prism.Regions.Behaviors.RegionCreationException was unhandled by user code
  Message=An exception occurred while creating a region with name 'ActionsRegion'. The exception was: System.Collections.Generic.KeyNotFoundException: controlType
   at Microsoft.Practices.Prism.Regions.RegionAdapterMappings.GetMapping(Type controlType) in c:\release\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism\Regions\RegionAdapterMappings.cs:line 82
   at Microsoft.Practices.Prism.Regions.Behaviors.DelayedRegionCreationBehavior.CreateRegion(DependencyObject targetElement, String regionName) in c:\release\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism\Regions\Behaviors\DelayedRegionCreationBehavior.cs:line 136. 
  Source=Microsoft.Practices.Prism
  StackTrace:
       at Microsoft.Practices.Prism.Regions.Behaviors.DelayedRegionCreationBehavior.CreateRegion(DependencyObject targetElement, String regionName) in c:\release\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism\Regions\Behaviors\DelayedRegionCreationBehavior.cs:line 143
       at Microsoft.Practices.Prism.Regions.Behaviors.DelayedRegionCreationBehavior.TryCreateRegion() in c:\release\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism\Regions\Behaviors\DelayedRegionCreationBehavior.cs:line 118
       at Microsoft.Practices.Prism.Regions.Behaviors.DelayedRegionCreationBehavior.OnUpdatingRegions(Object sender, EventArgs e) in c:\release\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism\Regions\Behaviors\DelayedRegionCreationBehavior.cs:line 99
  InnerException: System.Collections.Generic.KeyNotFoundException
       Message=controlType
       Source=Microsoft.Practices.Prism
       StackTrace:
            at Microsoft.Practices.Prism.Regions.RegionAdapterMappings.GetMapping(Type controlType) in c:\release\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism\Regions\RegionAdapterMappings.cs:line 82
            at Microsoft.Practices.Prism.Regions.Behaviors.DelayedRegionCreationBehavior.CreateRegion(DependencyObject targetElement, String regionName) in c:\release\WorkingDir\PrismLibraryBuild\PrismLibrary\Desktop\Prism\Regions\Behaviors\DelayedRegionCreationBehavior.cs:line 136
       InnerException:

**Comment by salfab** [comment]
see : http://www.seesharp.ch/unity_mef_prism_mefcontrib/81
